### Autostart

exec-once = kitty -e sh -c '~/.config/hypr/shortcut.sh; exec $SHELL'
exec-once = nm-applet --indicator
exec-once = waybar
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprsunset
