### Looks and Feel

# https://wiki.hyprland.org/Configuring/Variables/#general

general {
	gaps_in = 0 		
	gaps_out = 0 		

	border_size = 4

	# https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
	col.active_border = rgb(e0b2e4) rgb(ff00ff) 60deg
	col.inactive_border = rgb(b2dbe4) rgb(00d4ff) 45deg

	# Resizing windows by clicking and draging borders
	resize_on_border = true

	# Tearing - https://wiki.hyprland.org/Configuring/Tearing/
	allow_tearing = false

	layout = scrolling
	#layout = dwindle
}



# https://wiki.hyprland.org/Configuring/Variables/#decoration

decoration {
	rounding = 5
	rounding_power = 2

	# Transparency of focused and unfocused windows
	active_opacity = 0.9
	inactive_opacity = 0.75

	shadow{
		enabled = true
		range = 5
		color =  rgb(FF9999)
	}

	# https://wiki.hyprland.org/Configuring/Variables/#blur
	blur {
		enabled = true
		size = 3
		passes = 2
		vibrancy =  0.1696
		
	}	
}

	# https://wiki.hyprland.org/Configuring/Variables/#animations
	animations {
		enabled = yes

	# https://wiki.hyprland.org/Configuring/Animations/

	bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = easeInOutElastic, 0.12,1,0.43,0.66
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
	animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
	}


#  https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}


#  https://wiki.hypr.land/Configuring/Scrolling-Layout/
scrolling {
    fullscreen_on_one_column = true
    column_width = 0.6
    focus_fit_method = 1
    direction = right
}



# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}


