### Windows and Workspaces rules

# https://wiki.hyprland.org/Configuring/Window-Rules/
# https://wiki.hyprland.org/Configuring/Workspace-Rules/


windowrule = float on, match:title .*Volume Control.* 	 				 # pavucontrol starts in floating state
windowrule = float on, match:title .*Rename.*							 # Thunar rename prompt starts in floating state
windowrule = fullscreen on, match:class .*org.qbittorrent.qBittorrent.* 	 # qBittorrent starts in fullscreen mode
# workspace = 2, layoutopt:direction:right



# No opacity
windowrule = opacity 1.11 overide, match:class .*firefox.*
windowrule = opacity 1.11 overide, match:class .*floorp.*
windowrule = opacity 1.11 overide, match:class .*libreoffice-writer.*
windowrule = opacity 1.11 overide, match:title .*Volume Control.*
windowrule = opacity 1.11 overide, match:title .*Rename.*





windowrule = max_size 1200 800, match:float 1 	# Floating windows open in max size 1200x800px
windowrule = center on, match:class .*Electron.*			# Popup windows from webcord (about opening web sites) appear at center
windowrule = center on, match:class .*Xdg-desktop-portal-gtk.* 		# Popup windows from Vivaldi (about seclect files) appear at center 
windowrule = min_size 600 400, match:class .*Electron.* 						# Minimal size of abowe widows

# Ignore maximize request from apps.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,titleL^$,xwayland:1,floating:1,fullscreen:0,pined:0
